server:
  port: 2763

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    sentinel:
      transport:
        port: 12763
        dashboard: localhost:8748
      datasource:
        ds:
          nacos:
            namespace: ${spring.cloud.nacos.discovery.namespace}
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow

feign:
  sentinel:
    enabled: true